Adding objects
alexander16108/Awesome-Books pull request #1
Opened 2021-07-12 19:09 UTC by alexander16108

We create a basic markup for the project and displayed all required for the project

2021-07-13 07:59 UTC, mikenath223 requested changes
Hello Team,

You've done pretty well so far!
But for a few issues, you are almost done with this. Hang in there!


## Required Changes ♻️
_Please check the comments under the review._
- [x] When a user clicks the Add book button a book should be added.
- [ ] Also, when the user clicks the delete book button the book should be removed from the list of books. 
- [ ] The list of books should be preserved in the browser memory using localStorage.
- [ ] Also, there is a bunch of commented code in the project.


Happy coding, Cheers! 🚀🚀

Do feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, whether it is valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-13 08:00 UTC, mikenath223 commented on js/book-list-tracker.js
> +// const list = 0;
- [ ]  Please remove these commented codeblocks. If you want to refer to previous code please use gitHistory.

2021-07-13 08:01 UTC, mikenath223 commented on index.html
> +  <input type="submit" id="add" value="Add">
- [ ] Please add the functionality that adds a new book when the user submits the form.

2021-07-13 08:02 UTC, mikenath223 commented on js/book-list-tracker.js
> +    <button >Remove</button>
- [ ] The remove book button should remove a book from the list of books.

2021-07-13 08:04 UTC, mikenath223 commented on js/book-list-tracker.js
> +
- [ ] Adding default books is optional but ensure that the list of books actually gets updated based on the user's actions. In addition, please persist the list of books in the browser's memory using **localStorage.**

2021-07-13 08:06 UTC, mikenath223 commented on js/book-list-tracker.js
> +}
-  [ ] OPTIONAL - Consider adding an event listener that listens to the [DOMContentLoaded event](https://developer.mozilla.org/en-US/docs/Web/API/Window/DOMContentLoaded_event) before displaying the books to ensure the DOM is first loaded.

2021-07-13 12:11 UTC, Dipeshtwis requested changes
Hi @alexander16108 and @ahzia, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

- N.A.

Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**_Dipesh Kumar_**

-------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project(check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-13 12:11 UTC, Dipeshtwis commented on js/book-list-tracker.js
> +// const userMessage = document.querySelector('popup-message p');
- [ ] I will suggest to remove the commented code since removing commented code make codebase more clean.

2021-07-13 12:11 UTC, Dipeshtwis commented on js/book-list-tracker.js
> +});
- [ ] After click on remove button, it seems the book disappear but it stays in localstorage and hence after refreshing the page, book shows again. See the below screenshot I have clicked on remove on the book named `the wind` written by `dip` but it still stays in localstorage and after refreshing it came back. Please fix this.

![Screenshot from 2021-07-13 17-33-20](https://user-images.githubusercontent.com/22434660/125448912-c871d058-a657-4bd8-b077-14760f7aa536.png)

2021-07-13 20:14 UTC, ahzia commented on js/book-list-tracker.js
> +// const userMessage = document.querySelector('popup-message p');
Thank You for your Review, I have Removed all commented codes.

2021-07-13 20:16 UTC, ahzia commented on js/book-list-tracker.js
> +});
I have made some changes to add and Remove functions now the future is working.
@Dipeshtwis can you if anything is missing because this is our last Review.
Thanks

2021-07-13 20:17 UTC, ahzia commented on js/book-list-tracker.js
> +// const list = 0;
I Removed all commented codes

2021-07-13 20:18 UTC, ahzia commented on index.html
> +  <input type="submit" id="add" value="Add">
I added the Functionality

2021-07-13 20:18 UTC, ahzia commented on js/book-list-tracker.js
> +    <button >Remove</button>
It is working now

2021-07-14 07:55 UTC, mikenath223 approved these changes
Hello there  

Your project is complete!  There is nothing else to say other than... it's time to merge it 🛳 
Congratulations! 🎉 

Happy coding. Cheers! 🚀🚀

If you feel something isn't clear enough you can leave a question or comment in the PR thread.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-14 08:20 UTC, merged